"""
Here is an example of opening viewers directly from spikeinterface objects : recording and sorting.

In this example, recording and sorting are fake ones generated by spikeinterface but of you course
you can use any format supported by spikeinterface.

Note that you can display any lazy preprocessor from
`spikeinterface.toolkit.preprocessing` (filtering, denoising, whittening, ...) so you can see immediatly
the clean signal.



"""

import argparse
import os

import ephyviewer
import spikeinterface.full as si

argparser = argparse.ArgumentParser(description="View Neuroscope data")
argparser.add_argument("--filename", "-f", type=str, help="Path to Neuroscope data")
args = argparser.parse_args()

recording = si.NeuroScopeRecordingExtractor(file_path=args.filename)
sig_source = ephyviewer.SpikeInterfaceRecordingSource(recording=recording)

filtered_recording = si.bandpass_filter(recording, freq_min=60.0, freq_max=100.0)
sig_filtered_source = ephyviewer.SpikeInterfaceRecordingSource(
    recording=filtered_recording
)

sorting = si.read_neuroscope_sorting(
    folder_path=os.path.dirname(args.filename),
    xml_file_path=args.filename.replace(".dat", ".xml"),
)
spike_source = ephyviewer.SpikeInterfaceSortingSource(sorting=sorting)

app = ephyviewer.mkQApp()
win = ephyviewer.MainViewer(debug=True, show_auto_scale=True)

view = ephyviewer.TraceViewer(source=sig_source, name="signals")
win.add_view(view)

view = ephyviewer.TraceViewer(source=sig_filtered_source, name="signals filtered")
win.add_view(view)

view = ephyviewer.SpikeTrainViewer(source=spike_source, name="spikes")
win.add_view(view)


win.show()
app.exec()
